### ISSUE TITLE
How TxT To PDF File?

### ISSUE THREAD

**Issue by tenglongwentian** [aspose-pdf/Aspose.PDF-for-Java#29]
How TxT To PDF File?

**Comment by farhan-raza** [comment]
@tenglongwentian You can convert a TXT file to a PDF document by following the approach explained over [this link](https://github.com/aspose-pdf/Aspose.PDF-for-Java/blob/master/Examples/src/main/java/com/aspose/pdf/examples/AsposePdfExamples/DocumentConversion/ConvertTextFileToPDFFormat.java). Please download the Example project from this repository and run examples in your environment. In case you face any problem setting it up, then please visit the documentation article: [How to Run the Examples](https://docs.aspose.com/display/pdfjava/How+to+Run+the+Examples). To learn more about Aspose.PDF for Java API, you may visit [API documentation](https://docs.aspose.com/display/pdfjava/Home).
**PS**: I am Farhan Raza and I work as Developer Evangelist at Aspose.
