### ISSUE TITLE
Files used in documentation not available in repository

### ISSUE THREAD

**Issue by teja463** [aspose-pdf/Aspose.PDF-for-Java#30]
Some files which are used in documentation and for demo pupose in the code does not exist in the repository. For instance EmailDemo_updated.html which is used to demo converting html file to PDF does not exists in the repository. There are many examples like this.

**Comment by farhan-raza** [comment]
@teja463, Thank you for highlighting the missing file. We have updated the repository and mentioned file is not missing anymore. We will review it for other missing files soon. However, if you notice any other file missing then please feel free to report it to us and we will take care of it. 

PS: I work with Aspose as Developer Evangelist.
